// Code generated by go-zserio. DO NOT EDIT.

package schema

import ()

const ()

type DoubleSubtypedFloat64 SubtypedFloat64
type SubtypedFloat64 float64
type SubtypedInt32 int32
type SubtypedVarUint64 uint64
