package zserio

import "github.com/icza/bitio"

// Unmarshaler is the interface implemented by types that can be read from a
// zserio bitstream. The implementation is normally automatically generated
// by the zserio compiler.
type Unmarshaler interface {
	UnmarshalZserio(r *bitio.Reader) error
}

// Marshaler is the interface implemented by types that can be serialize
// themselves to a zserio bitstream. The implementation is normally automatically
// generated by the zserio compiler.
type Marshaler interface {
	MarshalZserio(w *bitio.Writer) error
	ZserioBitSize(bitPosition int) (int, error)
}
