package zserio

import "io"

// Aligner aligns the reader or writer with the byte boundary and returns the
// total of number of bits that have been skipped and an error if ocurred
// during skipping.
type Aligner interface {
	Align(boundary uint8) (int64, error)
}

type BitReader interface {
	Aligner

	ReadBits(n uint8) (uint64, error)
	ReadBool() (bool, error)
}

type Reader interface {
	io.Reader
	io.ByteReader
	BitReader
}

type BitWriter interface {
	Aligner

	WriteBits(r uint64, n uint8) error
	WriteBool(bool) error
	WriteBitsUnsafe(r uint64, n uint8) error
}

type Writer interface {
	io.Writer
	io.ByteWriter
	BitWriter
}

// Unmarshaler is the interface implemented by types that can be read from a
// zserio bitstream. The implementation is normally automatically generated
// by the zserio compiler.
type Unmarshaler interface {
	UnmarshalZserio(r Reader) error
}

// Marshaler is the interface implemented by types that can be serialized
// themselves to a zserio bitstream. The implementation is normally automatically
// generated by the zserio compiler.
type Marshaler interface {
	MarshalZserio(w Writer) error
	ZserioBitSize(bitPosition int) (int, error)
}

type ZserioType interface {
	Marshaler
	Unmarshaler
	Clone() ZserioType
}

type PackableUnmarshaler interface {
	ZserioCreatePackingContext(contextNode *PackingContextNode) error
	UnmarshalZserioPacked(contextNode *PackingContextNode, r Reader) error
}

type PackableMarshaler interface {
	MarshalZserioPacked(contextNode *PackingContextNode, w Writer) error
	ZserioInitPackingContext(contextNode *PackingContextNode) error
	ZserioInitializeOffsetsPacked(contextNode *PackingContextNode, bitPosition int) int
	ZserioBitSizePacked(contextNode *PackingContextNode, bitPosition int) (int, error)
}

type PackableZserioType interface {
	ZserioType
	PackableMarshaler
	PackableUnmarshaler
}
