package zserio

import "io"

// Aligner aligns the underlying strim to the byte boundary and returns the
// number of bits that have been read or written since the beginning.
type Aligner interface {
	Align(boundary uint8) (int64, error)
}

// Reader is used to read at the bit level and allows to align the stream to
// the byte boundary at any stage and get the number of bits read.
type Reader interface {
	io.ByteReader
	io.Reader
	Aligner

	ReadBits(n uint8) (uint64, error)
	ReadBool() (bool, error)
}

// Writer is used to write at the bit level and allows to align the stream to
// the byte boundary at any stage and get the number of bits written.
type Writer interface {
	io.ByteWriter
	io.Writer
	Aligner

	WriteBits(r uint64, n uint8) error
	WriteBitsUnsafe(r uint64, n uint8) error
	WriteBool(b bool) error
}

// Unmarshaler is the interface implemented by types that can be read from a
// zserio bitstream. The implementation is normally automatically generated
// by the zserio compiler.
type Unmarshaler interface {
	UnmarshalZserio(r Reader) error
}

// Marshaler is the interface implemented by types that can be serialized
// themselves to a zserio bitstream. The implementation is normally automatically
// generated by the zserio compiler.
type Marshaler interface {
	MarshalZserio(w Writer) error
	ZserioBitSize(bitPosition int) (int, error)
}

type ZserioType interface {
	Marshaler
	Unmarshaler
}

type PackableUnmarshaler interface {
	ZserioCreatePackingContext(contextNode *PackingContextNode) error
	UnmarshalZserioPacked(contextNode *PackingContextNode, r Reader) error
}

type PackableMarshaler interface {
	MarshalZserioPacked(contextNode *PackingContextNode, w Writer) error
	ZserioInitPackingContext(contextNode *PackingContextNode) error
	ZserioInitializeOffsetsPacked(contextNode *PackingContextNode, bitPosition int) int
	ZserioBitSizePacked(contextNode *PackingContextNode, bitPosition int) (int, error)
}

type PackableZserioType[B any] interface {
	ZserioType
	PackableMarshaler
	PackableUnmarshaler
	*B
}
