package zserio

import "io"

type Reader interface {
	io.Reader
	io.ByteReader

	ReadBits(n uint8) (uint64, error)
	ReadBool() (bool, error)
	Align(boundary uint8) error
}

type Writer interface {
	io.Writer
	io.ByteWriter

	WriteBits(r uint64, n uint8) error
	WriteBool(bool) error
	WriteBitsUnsafe(r uint64, n uint8) error
	Align(boundary uint8) error
}

// Unmarshaler is the interface implemented by types that can be read from a
// zserio bitstream. The implementation is normally automatically generated
// by the zserio compiler.
type Unmarshaler interface {
	UnmarshalZserio(r Reader) error
}

// Marshaler is the interface implemented by types that can be serialized
// themselves to a zserio bitstream. The implementation is normally automatically
// generated by the zserio compiler.
type Marshaler interface {
	MarshalZserio(w Writer) error
	ZserioBitSize(bitPosition int) (int, error)
}

type ZserioType interface {
	Marshaler
	Unmarshaler
	Clone() ZserioType
}

type PackableUnmarshaler interface {
	ZserioCreatePackingContext(contextNode *PackingContextNode) error
	UnmarshalZserioPacked(contextNode *PackingContextNode, r Reader) error
}

type PackableMarshaler interface {
	MarshalZserioPacked(contextNode *PackingContextNode, w Writer) error
	ZserioInitPackingContext(contextNode *PackingContextNode) error
	ZserioInitializeOffsetsPacked(contextNode *PackingContextNode, bitPosition int) int
	ZserioBitSizePacked(contextNode *PackingContextNode, bitPosition int) (int, error)
}

type PackableZserioType interface {
	ZserioType
	PackableMarshaler
	PackableUnmarshaler
}
